config/routes.rb
Cbtg::Application.routes.draw do

  resources :directors

  resources :recebimentos

  resources :rents

  resources :pagamentos

  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox
  resources :ocurrences

  resources :saloons

  resources :eventos

  resources :categories

  resources :grupos

  resources :provas

  resources :modalidades

  resources :piquetes

  resources :tpevents

  resources :tiposocs

  resources :tipodirs

  resources :functions

  resources :mtgs

  resources :rts

  resources :ctgs

  resources :members

  resources :socios

 root :to => redirect("/members")

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/ctg.rb
class Ctg < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :members
  has_many :piquetes
  belongs_to :rt
end

app/models/director.rb
class Director < ActiveRecord::Base
  belongs_to :member
  belongs_to :function
end

app/models/evento.rb
class Evento < ActiveRecord::Base
    mount_uploader :imagem, PictureUploader
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :directors
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  uploads_one :picture, thumb: [45, 40], small: [150, 200], regular: [580, 240], full: [1280, 493]
  belongs_to :ctg
  belongs_to :tiposoc
  has_many :ocurrences
  has_many :directors
end

app/models/modalidade.rb
class Modalidade < ActiveRecord::Base
end

app/models/mtg.rb
class Mtg < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :rts
end

app/models/ocurrence.rb
class Ocurrence < ActiveRecord::Base
  belongs_to :member
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
end

app/models/piquete.rb
class Piquete < ActiveRecord::Base
  belongs_to :ctg
end

app/models/prova.rb
class Prova < ActiveRecord::Base
end

app/models/recebimento.rb
class Recebimento < ActiveRecord::Base
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :saloon
end

app/models/rt.rb
class Rt < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :ctgs
  belongs_to :mtg
end

app/models/saloon.rb
class Saloon < ActiveRecord::Base
  has_many :rents
end

app/models/tipodir.rb
class Tipodir < ActiveRecord::Base
end

app/models/tiposoc.rb
class Tiposoc < ActiveRecord::Base
  has_many :members
end

app/models/tpevent.rb
class Tpevent < ActiveRecord::Base
end

app/controllers/recebimentos_controller.rb
class RecebimentosController < ApplicationController
  before_action :set_recebimento, only: [:show, :edit, :update, :destroy]

  # GET /recebimentos
  # GET /recebimentos.json
  def index
    @recebimentos = Recebimento.all
  end

  # GET /recebimentos/1
  # GET /recebimentos/1.json
  def show
  end

  # GET /recebimentos/new
  def new
    @recebimento = Recebimento.new
  end

  # GET /recebimentos/1/edit
  def edit
  end

  # POST /recebimentos
  # POST /recebimentos.json
  def create
    @recebimento = Recebimento.new(recebimento_params)

    respond_to do |format|
      if @recebimento.save
        format.html { redirect_to @recebimento, notice: 'Recebimento was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recebimento }
      else
        format.html { render action: 'new' }
        format.json { render json: @recebimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recebimentos/1
  # PATCH/PUT /recebimentos/1.json
  def update
    respond_to do |format|
      if @recebimento.update(recebimento_params)
        format.html { redirect_to @recebimento, notice: 'Recebimento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recebimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recebimentos/1
  # DELETE /recebimentos/1.json
  def destroy
    @recebimento.destroy
    respond_to do |format|
      format.html { redirect_to recebimentos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recebimento
      @recebimento = Recebimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recebimento_params
      params.require(:recebimento).permit(:vencimento, :quem, :valor, :dtpgto, :contato)
    end
end

app/controllers/rts_controller.rb
class RtsController < ApplicationController
  before_action :set_rt, only: [:show, :edit, :update, :destroy]

  # GET /rts
  def index
    if params[:busca].present?
      @rts = Rt.where("name LIKE ?", "%#{params[:busca][:name]}%")
    else
      @rts = Rt.all
    end
  end

  # GET /rts/1
  def show
  end

  # GET /rts/new
  def new
    @rt = Rt.new
  end

  # GET /rts/1/edit
  def edit
  end

  # POST /rts
  def create
    @rt = Rt.new(rt_params)

    if @rt.save
      redirect_to @rt, notice: 'Rt was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rts/1
  def update
    if @rt.update(rt_params)
      redirect_to @rt, notice: 'Rt was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /rts/1
  def destroy
    @rt.destroy
    redirect_to rts_url, notice: 'Rt was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rt
      @rt = Rt.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rt_params
      params.require(:rt).permit(:name, :end, :bairro, :cidade, :uf, :cep, :url, :email, :tel1, :tel2, :cel, :fundacao, :filiacao, :logo, :endcor, :bairrocor, :cepcor, :cidadecor, :ufcor, :cnpj, :obs, :mtg_id)
    end
end

app/views/recebimentos/_form.html.slim
= simple_form_for(@recebimento) do |f|
  = f.error_notification

  .form-inputs
    = f.input :vencimento
    = f.input :quem
    = f.input :valor
    = f.input :dtpgto
    = f.input :contato

  .form-actions
    = f.button :submit

app/views/recebimentos/edit.html.slim
h1 Editar recebimento

== render 'form'

= link_to 'Ver', @recebimento
'|
= link_to 'Voltar', recebimentos_path

app/views/recebimentos/index.html.slim
h1 Lista de Recebimentos

table.table.table-striped
  tr
    th Data de Vencimento
    th Quem
    th Valor
    th Data de Pagamento
    th Contato
    th


  - @recebimentos.each do |recebimento|
    tr
      td = l recebimento.vencimento, start_year: 2000, end_year: 2020
      td = recebimento.quem
      td = recebimento.valor
      td = l recebimento.dtpgto, start_year: 2013, end_year: 2020
      td = recebimento.contato
      td
          .btn-group.pull-right
            = link_to 'Ver', recebimento, class: 'btn btn-default btn-sm'
            = link_to 'Editar', edit_recebimento_path(recebimento), class: 'btn btn-default btn-sm'
            = link_to 'Deletar', recebimento, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-default btn-sm'

br

= link_to 'Novo Recebimento', new_recebimento_path, class: 'btn btn-danger'

app/views/recebimentos/new.html.slim
h1 Novo recebimento

== render 'form'

= link_to 'Voltar', recebimentos_path

app/views/recebimentos/show.html.slim
p#notice = notice

p
  strong Data deVencimento<br />
  = @recebimento.vencimento
p
  strong Quem<br />
  = @recebimento.quem
p
  strong Valor<br />
  = @recebimento.valor
p
  strong Data de Pagamento<br />
  = @recebimento.dtpgto
p
  strong Contato:
  = @recebimento.contato

= link_to 'Editar', edit_recebimento_path(@recebimento)
'|
= link_to 'Voltar', recebimentos_path