config/routes.rb
Cbtg::Application.routes.draw do

  resources :directors

  resources :recebimentos

  resources :rents

  resources :pagamentos

  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox
  resources :ocurrences

  resources :saloons

  resources :eventos

  resources :categories

  resources :grupos

  resources :provas

  resources :modalidades

  resources :piquetes

  resources :tpevents

  resources :tiposocs

  resources :tipodirs

  resources :functions

  resources :mtgs

  resources :rts

  resources :ctgs

  resources :members

  resources :socios

 root :to => redirect("/members")

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/ctg.rb
class Ctg < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :members
  has_many :piquetes
  belongs_to :rt
end

app/models/director.rb
class Director < ActiveRecord::Base
  belongs_to :member
  belongs_to :function
end

app/models/evento.rb
class Evento < ActiveRecord::Base
    mount_uploader :imagem, PictureUploader
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :directors
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  uploads_one :picture, thumb: [45, 40], small: [150, 200], regular: [580, 240], full: [1280, 493]
  belongs_to :ctg
  belongs_to :tiposoc
  has_many :ocurrences
  has_many :directors
end

app/models/modalidade.rb
class Modalidade < ActiveRecord::Base
end

app/models/mtg.rb
class Mtg < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :rts
end

app/models/ocurrence.rb
class Ocurrence < ActiveRecord::Base
  belongs_to :member
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
end

app/models/piquete.rb
class Piquete < ActiveRecord::Base
  belongs_to :ctg
end

app/models/prova.rb
class Prova < ActiveRecord::Base
end

app/models/recebimento.rb
class Recebimento < ActiveRecord::Base
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :saloon
end

app/models/rt.rb
class Rt < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :ctgs
  belongs_to :mtg
end

app/models/saloon.rb
class Saloon < ActiveRecord::Base
  has_many :rents
end

app/models/tipodir.rb
class Tipodir < ActiveRecord::Base
end

app/models/tiposoc.rb
class Tiposoc < ActiveRecord::Base
  has_many :members
end

app/models/tpevent.rb
class Tpevent < ActiveRecord::Base
end

app/controllers/piquetes_controller.rb
class PiquetesController < ApplicationController
  before_action :set_piquete, only: [:show, :edit, :update, :destroy]

  # GET /piquetes
  def index
    @piquetes = Piquete.all
  end

  # GET /piquetes/1
  def show
  end

  # GET /piquetes/new
  def new
    @piquete = Piquete.new
  end

  # GET /piquetes/1/edit
  def edit
  end

  # POST /piquetes
  def create
    @piquete = Piquete.new(piquete_params)

    if @piquete.save
      redirect_to @piquete, notice: 'Piquete was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /piquetes/1
  def update
    if @piquete.update(piquete_params)
      redirect_to @piquete, notice: 'Piquete was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /piquetes/1
  def destroy
    @piquete.destroy
    redirect_to piquetes_url, notice: 'Piquete was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piquete
      @piquete = Piquete.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def piquete_params
      params.require(:piquete).permit(:name, :ctg_id)
    end
end

app/controllers/rts_controller.rb
class RtsController < ApplicationController
  before_action :set_rt, only: [:show, :edit, :update, :destroy]

  # GET /rts
  def index
    if params[:busca].present?
      @rts = Rt.where("name LIKE ?", "%#{params[:busca][:name]}%")
    else
      @rts = Rt.all
    end
  end

  # GET /rts/1
  def show
  end

  # GET /rts/new
  def new
    @rt = Rt.new
  end

  # GET /rts/1/edit
  def edit
  end

  # POST /rts
  def create
    @rt = Rt.new(rt_params)

    if @rt.save
      redirect_to @rt, notice: 'Rt was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rts/1
  def update
    if @rt.update(rt_params)
      redirect_to @rt, notice: 'Rt was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /rts/1
  def destroy
    @rt.destroy
    redirect_to rts_url, notice: 'Rt was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rt
      @rt = Rt.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rt_params
      params.require(:rt).permit(:name, :end, :bairro, :cidade, :uf, :cep, :url, :email, :tel1, :tel2, :cel, :fundacao, :filiacao, :logo, :endcor, :bairrocor, :cepcor, :cidadecor, :ufcor, :cnpj, :obs, :mtg_id)
    end
end

app/views/piquetes/_form.html.slim
= simple_form_for(@piquete) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, label: 'Piquete'
    = f.association :ctg, label: 'CTG'

  .form-actions
    = f.button :submit

app/views/piquetes/edit.html.slim
h1 Piquete

== render 'form'

hr
.row
  .col-md-3
    = link_to 'Ver', @piquete, class: 'btn btn-danger'
  .col-md-3
    = link_to 'Voltar', piquetes_path, class: 'btn btn-danger'

app/views/piquetes/index.html.slim
h1 Piquetes

table.table.table-striped
  tr
    th Piquete
    th CTG
    th


  - @piquetes.each do |piquete|
    tr
      td = piquete.name
      td = piquete.ctg.name
      td
          .btn-group.pull-right

            = link_to 'Ver', piquete, class: 'btn btn-default btn-sm'
            = link_to 'Editar', edit_piquete_path(piquete), class: 'btn btn-default btn-sm'
            = link_to 'Deletar', piquete, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-default btn-sm'

hr

= link_to 'Novo Piquete', new_piquete_path, class: 'btn btn-danger'

app/views/piquetes/new.html.slim
h1 Novo Piquete

== render 'form'
hr
= link_to 'Voltar', piquetes_path, class: 'btn btn-danger'

app/views/piquetes/show.html.slim
p#notice = notice

p
  strong Piquete<br />
  = @piquete.name
hr
.row
  .col-md-2
    = link_to 'Editar', edit_piquete_path(@piquete), class: 'btn btn-danger'
  .col-md-2
    = link_to 'Voltar', piquetes_path, class: 'btn btn-danger'