config/routes.rb
Cbtg::Application.routes.draw do

  resources :directors

  resources :recebimentos

  resources :rents

  resources :pagamentos

  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox
  resources :ocurrences

  resources :saloons

  resources :eventos

  resources :categories

  resources :grupos

  resources :provas

  resources :modalidades

  resources :piquetes

  resources :tpevents

  resources :tiposocs

  resources :tipodirs

  resources :functions

  resources :mtgs

  resources :rts

  resources :ctgs

  resources :members

  resources :socios

 root :to => redirect("/members")

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/ctg.rb
class Ctg < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :members
  has_many :piquetes
  belongs_to :rt
end

app/models/director.rb
class Director < ActiveRecord::Base
  belongs_to :member
  belongs_to :function
end

app/models/evento.rb
class Evento < ActiveRecord::Base
    mount_uploader :imagem, PictureUploader
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :directors
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  uploads_one :picture, thumb: [45, 40], small: [150, 200], regular: [580, 240], full: [1280, 493]
  belongs_to :ctg
  belongs_to :tiposoc
  has_many :ocurrences
  has_many :directors
end

app/models/modalidade.rb
class Modalidade < ActiveRecord::Base
end

app/models/mtg.rb
class Mtg < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :rts
end

app/models/ocurrence.rb
class Ocurrence < ActiveRecord::Base
  belongs_to :member
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
end

app/models/piquete.rb
class Piquete < ActiveRecord::Base
  belongs_to :ctg
end

app/models/prova.rb
class Prova < ActiveRecord::Base
end

app/models/recebimento.rb
class Recebimento < ActiveRecord::Base
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :saloon
end

app/models/rt.rb
class Rt < ActiveRecord::Base
  mount_uploader :logo, PictureUploader
  has_many :ctgs
  belongs_to :mtg
end

app/models/saloon.rb
class Saloon < ActiveRecord::Base
  has_many :rents
end

app/models/tipodir.rb
class Tipodir < ActiveRecord::Base
end

app/models/tiposoc.rb
class Tiposoc < ActiveRecord::Base
  has_many :members
end

app/models/tpevent.rb
class Tpevent < ActiveRecord::Base
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_pagamento, only: [:show, :edit, :update, :destroy]

  # GET /pagamentos
  # GET /pagamentos.json
  def index
    if params[:filtro] == 'dia'
      @pagamentos = Pagamento.where(dtpgto: Date.today)
    elsif params[:filtro] == 'mes'
      @pagamentos = Pagamento.where(dtpgto: ((Date.today)..Date.today + 1.month))
    elsif params[:filtro] == 'amanha'
      @pagamentos = Pagamento.where(dtpgto: (Date.today + 1.day))

    else
      @pagamentos = Pagamento.all
    end

  end

  # GET /pagamentos/1
  # GET /pagamentos/1.json
  def show
  end

  # GET /pagamentos/new
  def new
    @pagamento = Pagamento.new
  end

  # GET /pagamentos/1/edit
  def edit
  end

  # POST /pagamentos
  # POST /pagamentos.json
  def create
    @pagamento = Pagamento.new(pagamento_params)

    respond_to do |format|
      if @pagamento.save
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pagamento }
      else
        format.html { render action: 'new' }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pagamentos/1
  # PATCH/PUT /pagamentos/1.json
  def update
    respond_to do |format|
      if @pagamento.update(pagamento_params)
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagamentos/1
  # DELETE /pagamentos/1.json
  def destroy
    @pagamento.destroy
    respond_to do |format|
      format.html { redirect_to pagamentos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagamento
      @pagamento = Pagamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagamento_params
      params.require(:pagamento).permit(:vencimento, :quem, :valor, :dtpgto, :tipopgto)
    end
end

app/controllers/rts_controller.rb
class RtsController < ApplicationController
  before_action :set_rt, only: [:show, :edit, :update, :destroy]

  # GET /rts
  def index
    if params[:busca].present?
      @rts = Rt.where("name LIKE ?", "%#{params[:busca][:name]}%")
    else
      @rts = Rt.all
    end
  end

  # GET /rts/1
  def show
  end

  # GET /rts/new
  def new
    @rt = Rt.new
  end

  # GET /rts/1/edit
  def edit
  end

  # POST /rts
  def create
    @rt = Rt.new(rt_params)

    if @rt.save
      redirect_to @rt, notice: 'Rt was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rts/1
  def update
    if @rt.update(rt_params)
      redirect_to @rt, notice: 'Rt was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /rts/1
  def destroy
    @rt.destroy
    redirect_to rts_url, notice: 'Rt was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rt
      @rt = Rt.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rt_params
      params.require(:rt).permit(:name, :end, :bairro, :cidade, :uf, :cep, :url, :email, :tel1, :tel2, :cel, :fundacao, :filiacao, :logo, :endcor, :bairrocor, :cepcor, :cidadecor, :ufcor, :cnpj, :obs, :mtg_id)
    end
end

app/views/pagamentos/_form.html.slim
= simple_form_for(@pagamento) do |f|
  = f.error_notification

  .form-inputs
    = f.input :vencimento
    = f.input :quem
    = f.input :valor
    = f.input :dtpgto, label: 'Data de pagamento'
    = f.input :tipopgto, label: 'Tipo pagamento'

  .form-actions
    = f.button :submit

app/views/pagamentos/edit.html.slim
h1 Editar pagamento

== render 'form'

= link_to 'Ver', @pagamento
'|
= link_to 'Voltar', pagamentos_path

app/views/pagamentos/index.html.slim
h1 Pagamentos
.row
  .col-md-2
    .btn.btn-default
      = link_to 'Todos',  pagamentos_path
  .col-md-2
    .btn.btn-default
      = link_to 'No mês',  pagamentos_path(filtro: 'mes')
  .col-md-2
    .btn.btn-default
      = link_to 'No dia',  pagamentos_path(filtro: 'dia')
  .col-md-2
    .btn.btn-default
      = link_to 'Amanhã',  pagamentos_path(filtro: 'amanha')

<br />
table.table.table-striped
  tr
    th Vencimento
    th Quem
    th Valor
    th Data pagamento
    th Tipo pagamento
    th


  - @pagamentos.each do |pagamento|
    tr
      td = l pagamento.vencimento
      td = pagamento.quem
      td = pagamento.valor
      td = l pagamento.dtpgto
      td = pagamento.tipopgto
      td
          .btn-group.pull-right
            = link_to 'Ver', pagamento, class: 'btn btn-default btn-sm'
            = link_to 'Editar', edit_pagamento_path(pagamento), class: 'btn btn-default btn-sm'
            = link_to 'Deletar', pagamento, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-default btn-sm'

br

= link_to 'Novo Pagamento', new_pagamento_path, class: 'btn btn-danger'

app/views/pagamentos/new.html.slim
h1 Novo pagamento

== render 'form'

= link_to 'Voltar', pagamentos_path

app/views/pagamentos/show.html.slim
p#notice = notice

p
  strong Vencimento<br />
  = @pagamento.vencimento
p
  strong Quem<br />
  = @pagamento.quem
p
  strong Valor<br />
  = @pagamento.valor
p
  strong Data pagamento<br />
  = @pagamento.dtpgto
p
  strong Tipo pagamento<br />
  = @pagamento.tipopgto

= link_to 'Editar', edit_pagamento_path(@pagamento)
'|
= link_to 'Voltar', pagamentos_path